title: "Smart Life Lab"
description: "Expertly curated life hacks for your daily efficiency."
remote_theme: pages-themes/architect@v0.2.0 # 시원하고 전문적인 디자인
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# 해외 타겟팅 설정
lang: en-US
url: "https://lak77777.github.io"
baseurl: "/lak777.github.io"
