title: "Global Life Hacks" # 구글 검색에 뜰 사이트 이름
description: "Professional life hacks and tips for daily efficiency."
url: "https://lak77777.github.io"
baseurl: "" # 아이디 중복 방지

# [핵심] 모든 글을 구글이 개별 페이지로 인식하게 함
permalink: /posts/:title/

# [SEO] 검색 엔진이 좋아하는 태그를 자동으로 생성
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap # 구글에 '내 글 목록 여기 있다'고 알려주는 지도

theme: minima
